server:
  port: 9080

mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty
      id-type: auto
  type-aliases-package: com.tabus.tabus.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      tabus:
        tabus:
          mapper: debug
          service: info
          controller: info


spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/tabus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true  # 启用文件上传（默认开启）
      max-file-size: 200MB  # 单个文件最大大小
      max-request-size: 500MB  # 总请求最大大小
      file-size-threshold: 0  # 文件写入磁盘的阈值（0 表示直接写入磁盘）
tabus:
  ai:
    hunyuan:
      api-key: vl3D7ojstoCDNli0VePZhNJszO1lGfSr  # 腾讯混元AI的API密钥
      assistant-id: bjkRHf7MsfKE  # 助手ID
      connection-timeout: 10
      read-timeout: 30
      write-timeout: 30
  video:
    upload-dir: "${user.dir}/upload-videos"  #项目根目录下的 upload-videos 文件夹
  ffmpeg:
    path: ""  # 使用绝对路径
  faceplusplus:
    api-key: j9oLmjVU94xLw3scQiTAOm8KBkbPNh3V
    api-url: https://api-cn.faceplusplus.com/facepp/v3/detect
    api-secret: IDv7KHddPFgdNH2MmcERpPekJ2bZBpyw